name: 'duseapp'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  angular: ">=1.1.0 <2.0.0"
  restpoint:
    git: git://github.com/Adracus/restpoint.git
  duse:
    git: git://github.com/duse-io/duse-dart.git
transformers:
- angular
