name: duseapp
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: '>=1.1.0 <2.0.0'
  angular_ui: any
  browser: any
  cipher: any
  crypto: any
  duse:
    git: git://github.com/duse-io/duse-dart.git
  restpoint:
    git: git://github.com/Adracus/restpoint.git
  web_components: '>=0.10.1 <0.11.0'
  stack_trace: '1.1.1'
transformers:
- angular:
    html_files:
    - lib/component/login.html
    - lib/component/register.html
